# fly.toml app configuration file generated for cv-mihai on 2024-08-31T19:37:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cv-mihai'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
